import sqlite3

conn = sqlite3.connect('book_db.sqlite')
cursor = conn.cursor()

cursor.execute("SELECT * FROM books")
record = cursor.fetchall()
for row in record:
    print(row)
print("------------------------------------------------------------")
cursor.execute('SELECT title FROM books WHERE author="William Shakespeare"')
record = cursor.fetchall()
print(record)
print("----------------------წიგნები, რომლის ავტორია როულინგი ან შექსპირი-------------------------------------")
cursor.execute('SELECT title FROM books WHERE author="William Shakespeare" OR author="Rowling"')
record = cursor.fetchall()
print(record)
print("--------------------------წიგნები, რომლის ფასი 20-ს არ აღემატება----------------------------------")
cursor.execute('SELECT title FROM books WHERE price<=20')
record = cursor.fetchall()
print(record)
print("---------------------------განსხვავებული ავტორები---------------------------------")
cursor.execute('SELECT DISTINCT author FROM books')
record = cursor.fetchall()
print(record)
print("-----------------------მომხმარებლის სახელები, რომლის ბალანსი 100-ზე ნაკლებია-------------------------------------")
cursor.execute('SELECT username FROM users WHERE balance>100')
record = cursor.fetchall()
print(record)
print("------------------------------------------------------------")
cursor.execute('SELECT username FROM users WHERE balance>100')
record = cursor.fetchall()
print(record)
print("------------------------------------------------------------")
cursor.execute('SELECT * FROM purchase WHERE strftime("%Y", (purchase_date, 8, 4) >2018')
record = cursor.fetchall()
print(record)
print("-------------------------იმ მომხმარებლის სახელები, რომლებსაც ერთი წიგნი მაინც აქვთ შესყიდული-----------------------------------")
cursor.execute('SELECT id, username, balance FROM users WHERE id IN (SELECT DISTINCT user_id FROM purchase)')
record = cursor.fetchall()
print(record)
print("-------------------------წიგნები, რომლებიც ერთხელ მაინც გაიყიდა-----------------------------------")
cursor.execute('SELECT id, title, author, price FROM books WHERE id IN (SELECT DISTINCT book_id FROM purchase)')
record = cursor.fetchall()
print(record)
print("-------------------------წიგნები, რომლებიც არცერთხელ გაყიდულა-----------------------------------")
cursor.execute('SELECT')
conn.close()